name: Build and Deploy to Render

on:
  push:
    branches: [ "master" ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - uses: actions/checkout@v4

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    # Step 3: Build the JAR file with Maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml

    # Step 4: Upload the JAR file as an artifact
    - name: Upload JAR file
      uses: actions/upload-artifact@v4
      with:
        name: myblog-jar
        path: target/myblog-*.jar

    # Step 5: Deploy to Render using the JAR
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        # Download the JAR artifact
        mkdir -p deployment
        curl -L -o deployment/app.jar "${{ steps.build.outputs.artifacts_url }}/myblog-jar"

        # Deploy to Render (adjust based on your Render setup)
        curl -X POST \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -F "serviceId=<YOUR_RENDER_SERVICE_ID>" \
          -F "sourceFile=@deployment/app.jar" \
          https://api.render.com/deploy
